kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      slack_api_url: <api url>

    # The directory from which notification templates are read.
    templates:
    - '/etc/alertmanager-template/*.tmpl'

    route:
      group_by: [cluster]
      # If an alert isn't caught by a route, send it slack.
      receiver: slack-all
      routes:
        - match:
            severity: slack
          receiver: slack-all


    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '#sockshop-ops'
        send_resolved: true
        api_url: <api url>
